### ISSUE TITLE
Test email connection

### ISSUE THREAD

**Issue by KevinBatdorf** [bytefury/crater#101]
**Is your feature request related to a problem? Please describe.**
The settings for MailGun seem incorrect as it requests the SMTP credentials and the API key. The fields don't seem very clear

**Describe the solution you'd like**
A "test email" button to check the connection is working would resolve any issues without having create and send an invoice to test it.

**Describe alternatives you've considered**
Can't think of any thing else :)

**Comment by adampatterson** [comment]
I was just entering the same problem.

I have used Mailgun with Laravel in the past and am a little familiar with the settings, in Crater, there are a lot more options for the configuration that I don't fully understand.

For example, Mail Host, Domain, and Mail Port. Normally I would enter my domain, and my API Key and I'm off.  

100% agree with the config options being mixed up and adding the ability to test would be amazing.

Because I can't test the mailgun config when I originally sent an invoice as a test I found that it did not work, and I was not able to resend it. I had to recreate the invoice in order to resend.

 Ref #100

**Comment by mohitpanjwani** [comment]
Thanks for reporting the issue. 

We are working on simplifying this. Also we have added the test email feature based on your feedback and it will be included in the next update. 👍

**Comment by macbookandrew** [comment]
I ran into the same issue with Mailgun and the settings fields not making sense based on my familiarity with using Mailgun in other Laravel projects. The settings fields sounded like they were asking for a combination of API and SMTP credentials.

I fixed email sending for now by manually editing my `.env` file as follows and running `php artisan config:cache`:

```
MAIL_FROM_ADDRESS=<my email address>
MAIL_FROM_NAME="<my name>"

MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=<my mailgun domain>
MAILGUN_SECRET=<my mailgun key>
MAILGUN_ENDPOINT=api.mailgun.net
```

**Comment by adampatterson** [comment]
I ultimately made the same changes adding bits until it worked.

I also noticed that I had repeating .env entries from multiple attempts previously to get it working.

**Comment by macbookandrew** [comment]
> I also noticed that I had repeating .env entries from multiple attempts previously to get it working.

Yes, I noticed the same as well.

**Comment by mohitpanjwani** [comment]
Thanks for the patience guys. This has been fixed on https://github.com/bytefury/crater/commit/d79692cf3bcfbb13b8fef806e69a8db0e9fff3d2
