### ISSUE TITLE
The PHP GD extension is required, but is not installed.

### ISSUE THREAD

**Issue by karnaf** [bytefury/crater#136]
I've installed the system manually, and when trying to create an invoice PDF, I got a 500 - Server Error.
When debugging, I found out that an exception is thrown, saying "The PHP GD extension is required, but is not installed."

It is suggested by dompdf in its composer.json, but not mandatory.

I guess it should be added to the list of required extensions in the setup pages check.

My environment:
Centos 7, PHP 7.3.13, Crater 2.1.0

**Comment by proea** [comment]
@karnaf Are you using docker or not?

**Comment by karnaf** [comment]
Docker indeed

Docker version 18.06.1-ce

**Comment by proea** [comment]
@karnaf could you provide the output from the following commands:
`docker-compose exec php php --ini`
`docker-compose exec php php -m`

**Comment by karnaf** [comment]
Modules (php -m)
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug
```

Config (php --ini)
```
Configuration File (php.ini) Path: /etc
Loaded Configuration File:         /etc/php.ini
Scan for additional .ini files in: /etc/php.d
Additional .ini files parsed:      /etc/php.d/15-xdebug.ini,
/etc/php.d/20-bcmath.ini,
/etc/php.d/20-bz2.ini,
/etc/php.d/20-calendar.ini,
/etc/php.d/20-ctype.ini,
/etc/php.d/20-curl.ini,
/etc/php.d/20-dom.ini,
/etc/php.d/20-exif.ini,
/etc/php.d/20-fileinfo.ini,
/etc/php.d/20-ftp.ini,
/etc/php.d/20-gd.ini,
/etc/php.d/20-gettext.ini,
/etc/php.d/20-iconv.ini,
/etc/php.d/20-json.ini,
/etc/php.d/20-mbstring.ini,
/etc/php.d/20-mysqlnd.ini,
/etc/php.d/20-pdo.ini,
/etc/php.d/20-phar.ini,
/etc/php.d/20-posix.ini,
/etc/php.d/20-shmop.ini,
/etc/php.d/20-simplexml.ini,
/etc/php.d/20-sockets.ini,
/etc/php.d/20-sqlite3.ini,
/etc/php.d/20-sysvmsg.ini,
/etc/php.d/20-sysvsem.ini,
/etc/php.d/20-sysvshm.ini,
/etc/php.d/20-tidy.ini,
/etc/php.d/20-tokenizer.ini,
/etc/php.d/20-xml.ini,
/etc/php.d/20-xmlwriter.ini,
/etc/php.d/20-xsl.ini,
/etc/php.d/30-mysqli.ini,
/etc/php.d/30-pdo_mysql.ini,
/etc/php.d/30-pdo_sqlite.ini,
/etc/php.d/30-wddx.ini,
/etc/php.d/30-xmlreader.ini,
/etc/php.d/40-imagick.ini,
/etc/php.d/40-ssh2.ini,
/etc/php.d/40-zip.ini
```

**Comment by karnaf** [comment]
Here are my current Dockerfile and docker-compose.yaml if it helps
(I've added TXT at the end so I could upload them here...)


[docker-compose.yaml.TXT](https://github.com/bytefury/crater/files/4122132/docker-compose.yaml.TXT)
[Dockerfile.TXT](https://github.com/bytefury/crater/files/4122133/Dockerfile.TXT)

**Comment by proea** [comment]
@karnaf looks pretty good, GD is installed.

Please provide a bit more details about the error "The PHP GD extension is required, but is not installed.". when/where/etc 

And of course you can use Dockerfile and docker-compose.yml located in the project. Otherwise, issue is specific to your custom environment (not the repository code), it is harder to diagnose and no one will support


p.s. my personal comments:
- It's better to use the official docker images for php: https://hub.docker.com/_/php (There are xdebug instructions, you can easily prepare and customize the container)
- Do not use 'RUN chkconfig httpd on', it is not necessary inside the container.
- 'ipv4_address' is too large in docker-compose.yml: subnet: 172.66.0.0/16. I would recommend /24
- chown -R apache: /var/www/html/crater should be enough. You don't need to use chmod -R 755 /var/www/html/... еtc. (I know there are extra lines in the current Dockerfile in the repository. I want to prepare a pull request later and fix the current Dockerfile)
- app volume is not used in the docker-compose.yml.

**Comment by karnaf** [comment]
First of all, thanks for taking the time to answer - I appreciate the comments. Always.

I have followed the [manual installation instructions](https://docs.craterapp.com/installation.html#manual-installation) and installed Crater 2.1.0 on a CentOS 7 image.
CentOS's PHP does not come by default with GD installed, so I had this problem.

The reason I'm using that option is that I'm modifying Crater and wanted to work in an environment I feel more comfortable with. I'm modifying Crater to match some legislation issues and some features I need. For example:

- Adding the seller's & buyer's tax ID to invoices (a must for me...)
- Adding a digital signature to documents
- Adding more details to expenses (e.g. supporting other currencies or more details of the provider)

Cheers

**Comment by proea** [comment]
@karnaf, thanks for the answer.

Try to build a container with the current docker-compose.yml and Dockerfile. Everything should work!
