### ISSUE TITLE
Credit & Copyright Akaunting

### ISSUE THREAD

**Issue by denisdulici** [bytefury/crater#209]
Hi there,

Several files/functions have been copy-pasted from [Akaunting](https://github.com/akaunting/akaunting). For example, this [commit](https://github.com/bytefury/crater/commit/e31b60bc48be375dc591590194e5f2a4758976c7).

Please, add Akaunting to credits and put copyright notice to license and respected files/functions as per the GPL requirement.

Regards

**Comment by mohitpanjwani** [comment]
Hi @denisdulici, 

We've certainly taken inspiration from Akunting for the self-update module of our app. We can definitely wish to credit where its due. 

We've modified the code according to our needs, and haven't copy-pasted everything. 

We cannot update our License but we can add credits on the files and also on our repository. 

Would that be ok with you?

**Comment by denisdulici** [comment]
You use AAL so yes, that would make it really complicated. Feel free to skip that part.

One of our users reported that commit but it seems there are more like [this](https://github.com/bytefury/crater/blob/master/app/Space/SiteApi.php) or [this](https://github.com/bytefury/crater/blob/master/app/Listeners/Updates/Listener.php) one. I'm not gonna check all repo as I believe you know your code better and would add it where it's required.

BTW, I'm not against copy-paste as that's part of the spirit of open-source 😉 

Lastly, it seems you've done a great job here, congrats.

**Comment by mohitpanjwani** [comment]
Thank you for your kind words @denisdulici, 

Really love the work you've done on Akaunting.

We'll add the credit on the self-update classes which were derived from your project, as well as our repository page. 

Have a nice day 👍

**Comment by mohitpanjwani** [comment]
Added credit for derived files as discussed:
https://github.com/bytefury/crater/commit/dc37f565c415232e90387f0dd5f0d800c605cae4
https://github.com/bytefury/crater/commit/dc37f565c415232e90387f0dd5f0d800c605cae4

**Comment by test2a** [comment]
@denisdulici sorry for being a party pooper but imo your original assertion on license because the virality of GPL from akaunting must flow into crater and crater needs to get gpl license in its code. 
@mohitpanjwani don't want to blame you or anything but since you have already acknowledged that code has been copied from akaunting, GPL states that all derivatives of GPL code must use GPL or its derivative license. its immaterial you only credited the original work. 
https://softwareengineering.stackexchange.com/questions/342156/can-i-use-some-gpl-code-in-lgpl-project
"The combination of GPL code and LGPL code must be licensed under the GPL. If you want to use that code, you'll have to change your license, or refrain from using it. If the other project would want their code to be used in LGPL projects, they'd have licensed it under the LGPL – I doubt they'll give you special permission."

this talks about mixing GPL with LGPL which is still a derivative of GPL. 
https://opensource.stackexchange.com/questions/1446/why-doesnt-this-gpl-loophole-work?newreg=b29b58436f7543248dbd2e163275f032

what my point is, that because this project already acknowledges that it uses code from akaunting which is GPL code, this project MUST be GPL.
