### ISSUE TITLE
App update fails in Docker

### ISSUE THREAD

**Issue by lawzava** [bytefury/crater#214]
**Describe the bug**
When doing app update in Docker (through web view) it crashes with "server error on migration"

**Expected behavior**
Update succeeds

Was trying to update from 3.0 to 3.1

**Comment by mohitpanjwani** [comment]
Hey, the docker setup has some issues so we've completely re-created the setup. 

Just completing the documentation now.. I'll update in a day or two with the given steps so you can successfully update your app. 

Thanks for the feedback btw 👍

**Comment by azaricstefan** [comment]
3.1.0 version fails on first run setup:

`user@server:~/crater# **docker-compose up -d**

Building php
Step 1/16 : FROM composer as composer
 ---> 700f5e704c9f
Step 2/16 : COPY composer.* /app/
 ---> Using cache
 ---> 5e6ae84838a5
Step 3/16 : COPY database /app/database
 ---> Using cache
 ---> f36472ee4d15
Step 4/16 : RUN composer install --no-scripts --no-suggest --no-interaction --prefer-dist --optimize-autoloader
 ---> Running in b96cf811d303
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/image 1.7.6 -> satisfiable by spatie/image[1.7.6].
    - spatie/image 1.7.6 requires ext-exif * -> the requested PHP extension exif is missing from your system.
  Problem 2
    - Installation request for spatie/pdf-to-image 2.0.1 -> satisfiable by spatie/pdf-to-image[2.0.1].
    - spatie/pdf-to-image 2.0.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
  Problem 3
    - spatie/image 1.7.6 requires ext-exif * -> the requested PHP extension exif is missing from your system.
    - spatie/laravel-medialibrary 7.19.3 requires spatie/image ^1.4.0 -> satisfiable by spatie/image[1.7.6].
    - Installation request for spatie/laravel-medialibrary 7.19.3 -> satisfiable by spatie/laravel-medialibrary[7.19.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php-cli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
ERROR: Service 'php' failed to build: The command '/bin/sh -c composer install --no-scripts --no-suggest --no-interaction --prefer-dist --optimize-autoloader' returned a non-zero code: 2`

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1

Please follow the following steps in order to update your current docker setup:

Take a backup of your database
Remove/stop your existing containers docker-compose down
pull the latest changes from this repository: git pull origin master
docker-compose up -d
Run the setup command to install composer dependencies and re-generate the keys: ./docker-compose/setup.sh
Run migrations: docker-compose exec app php artisan migrate
Update the version manually on settings table to 3.1.1
You should be good to go with above directions but if you face any issues, please feel free to re-open the issue.

**Comment by mohitpanjwani** [comment]
Fixed the issue on latest update: https://github.com/bytefury/crater/releases/tag/3.1.1

Please follow the following steps in order to update your current docker setup: 
- Take a backup of your database
- Remove/stop your existing containers `docker-compose down`
- pull the latest changes from this repository: `git pull origin master`
- docker-compose up -d
- Run the setup command to install composer dependencies and re-generate the keys: `./docker-compose/setup.sh`
- Run migrations: `docker-compose exec app php artisan migrate`
- Update the version manually on settings table to `3.1.1`

You should be good to go with the above steps but if you face any issues, please feel free to re-open the issue.

**Comment by azaricstefan** [comment]
@mohitpanjwani thank you for quick response! It works now!
