### ISSUE TITLE
Company ID / Tax ID

### ISSUE THREAD

**Issue by TheSkrypt** [bytefury/crater#246]
I would really appreciate if you could add your company ID and tax ID to your company information and display this information on your invoices. I'm legally obligated to display this information and I'm sure a lot of other people are too.

Currently, I had to add it manually to the template, but I fear that after updating the app the changes will be lost and I'd have to re-do it every update.

**Comment by mohitpanjwani** [comment]
Hey! so we're already working on custom fields which will allow this function as well as enable a ton of other possibilities.

it will be included in the next update.. hopefully by the end of August. 

<img width="252" alt="Screenshot 2020-08-01 at 12 31 37 PM" src="https://user-images.githubusercontent.com/8002555/89096274-14efe080-d3f3-11ea-85af-f3b10841f88f.png">
<img width="232" alt="Screenshot 2020-08-01 at 12 31 28 PM" src="https://user-images.githubusercontent.com/8002555/89096275-16210d80-d3f3-11ea-8d84-cbbd2bfdbb1c.png">

The update is taking time because it includes a lot of requested features and we've completely refactored the system in terms of code.  

It will include the following features:
- TailwindCSS 
- Backup ( Create backups with UI)
- Customer View page
- Custom Notes
- Unit & Feature Tests
 -API Documentation
- Edit Email Subject & Description with placeholders before sending out an Invoice or Estimate Email
- Custom Fields
- Multiple Admins support

**Comment by fukawi2** [comment]
Looking forward to seeing this one released.

**Comment by yehanny** [comment]
Any update from this release, do you need something from us to advance in this great features? Thanks!

**Comment by andrastudio** [comment]
Any update on this? Would be interested to use version 4 although if it's still in beta.

**Comment by azaricstefan** [comment]
This is available in V4 already. Maybe close this issue?

**Comment by mohitpanjwani** [comment]
Added on https://github.com/bytefury/crater/releases/tag/4.0.0
