### ISSUE TITLE
.htaccess

### ISSUE THREAD

**Issue by pledgeco** [bytefury/crater#284]
I'm using serverpilot for web application apps. They have a different structure for mapping than your setup.

They use "public" before root folder for public.

So the path is: /srv/users/serverpilot/apps/faktura-motiwise/public/public

```
You don't have permission to access this URL.

Possible causes of this error include:

The request was forbidden by rules in the .htaccess file.
The directory you requested does not have an index.html or index.php file.
The permissions on the file or directory are incorrect.

```
Our server is loooking for an .httacess in the root folder. What can we do here?:)

Best regards

**Comment by mohitpanjwani** [comment]
I think your web root should be `/srv/users/serverpilot/apps/faktura-motiwise/public/` instead of `/srv/users/serverpilot/apps/faktura-motiwise/public/public`. 

It seems like you've made a mistake in configuring the webroot path. 

I don't think there's any issue with Crater regarding this, so I'm closing this issue.
