### ISSUE TITLE
Manual Upadate?

### ISSUE THREAD

**Issue by secrethash** [bytefury/crater#36]
What are the steps for manually updating the application?

**Comment by mohitpanjwani** [comment]
What's the reason for manually updating the application if there's a way to automatically?

**Comment by secrethash** [comment]
See basically I had issues twice. I run two instances of crater ec2 on aws.

- **1st** _Managed by Runcloud_ : So as this instance is managed by Runcloud (not good), they have a limitation of disabling few of the PHP functions in the free account. One of them is `set_time_limit()` used in the update process.
- **2nd** _Managed by Moss.sh_ : So far the best for managing servers, no limitations and complete control. The thing happened when I clicked update on the application was that it installed the code base all over again, clearing out the vendor and node_modules directory. So my app was blank until I realised that I have to run `composer install` and `npm install` again. Also after I did that and went back to my app->settings->update page, there was an update available and app didn't get updated.

Currently inspecting the problem for the 2nd instance, no idea what went wrong.

**Comment by mohitpanjwani** [comment]
That's really weird!  

We don't have a way to do this manually yet, but I think it's possible to do this by cloning the github repository directly and then do a `git pull` everytime there's a new update. 

But then comes the issue of running event listeners for each update, which are responsible for updating the database and deleting unneeded files etc and updating the version in the settings table.

For that, we'll need to create a simple artisan command which fires an `UpdateFinished` event or something but I feel things will break when there have been 2 major updates. 

Thus, I think your best option is to install Crater on a server that doesn't have a problem with auto-updating. or let us know if there's any way we can improve the auto-update feature to support your web-service/server.

**Comment by mohitpanjwani** [comment]
From 3.1.0 onwards we have made a few changes to make it easier for everyone to update the application like: 
- We are now using laravel migrations to make database changes instead of event listeners
- We've divided the update process into multiple steps to make it easier to track the issue and also allow updating vendor files automatically
- We've redesigned the Update app UI 
- Added a new `crater:update` command to update the application from command-line

Here's how the UI looks like now: 
![update app screen](https://user-images.githubusercontent.com/8002555/82534225-6877bf80-9b62-11ea-993f-3fc55c04423f.png)

**Comment by mohitpanjwani** [comment]
I think with these changes, it should be pretty easy to manually update your application. 

However, we'll also add a page on craterapp.com to download update zip files just in case for users who cannot automatically update the app. 

I'll keep this issue open until that's done.
