### ISSUE TITLE
Where are the Cities?

### ISSUE THREAD

**Issue by AngelinCalu** [bytefury/crater#40]
Hello,

I'm checking to see if this is a good starting point for a future application and I can't wrap my head around this thing:

This is from `routes/api.php`:
```php
// Country, State & City
//----------------------------------

Route::get('/countries', [
    'as' => 'countries',
    'uses' => 'LocationController@getCountries'
]);

Route::get('/states/{id}', [
    'as' => 'states',
    'uses' => 'LocationController@getStates'
]);

Route::get('/cities/{id}', [
    'as' => 'cities',
    'uses' => 'LocationController@getCities'
]);
```

This is the whole app/Http/Controllers/LocationController.php:

```php
<?php
namespace Crater\Http\Controllers;

use Illuminate\Http\Request;
use Crater\Country;

class LocationController extends Controller
{
    public function getCountries()
    {
        return response()->json([
            'countries' => Country::all()
        ]);
    }
}
```

Where are the `getStates` and `getCities` methods called from? and where are the cities stored? 
There are also no tables for those created through migrations...

Related to #13 , #22, #38

**Comment by mohitpanjwani** [comment]
Hey! Thanks for finding the issue.

That's actually a silly mistake (we forgot to remove routes) because we removed states & cities selectors in the recent update and replaced them with text input fields.

Fixed in below commit: 
https://github.com/bytefury/crater/commit/283b910cc3657c8b3e320cea7f42e3338f0be2b5
