### ISSUE TITLE
Error when displaying company logo

### ISSUE THREAD

**Issue by nenoken** [bytefury/crater#403]
**Describe the bug**
Error to display company logo, image src url on settings and email send.

<img class="header-logo" src="{{asset($data['company']['logo'])}}" alt="{{$data['company']['name']}}">

`<img class="header-logo" src="{{asset($data['company']['logo'])}}" alt="{{$data['company']['name']}}">`

this show the ALT text, but the url is:
_var/www/crater/storage/app/public/7/mylogo.png_

**Expected behavior**

the url should look like this
{APP_URL}/storage/7/mylogo.png

**Screenshots**

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: 10.2.31-MariaDB

**Optional info**
- OS:  Ubuntu
- Browser: chrome

**Comment by leonceaklin** [comment]
I have the same issue. When I try open the image in the browser it redirects me to the main page.

**Comment by captaincoo1** [comment]
I'm having this issue too.

**Comment by calumshep** [comment]
Also having this issue. The view for the company settings page sets the logo preview src to the user's company logo attribute, instead of getting the asset URL of it in the public storage directory. It's not a simple fix as this data is loaded directly from the relationship with the user in the `getUser()` method of the `CompanyController` which is what the action uses to fetch the values to display.

**Comment by kostaspapad** [comment]
I had the same issue on my local test machine, to solve it I edited the linux /etc/hosts file and added a new entry: 
`127.0.0.1 crater.test` <- your name domain here

**Comment by nothinghalosix** [comment]
same issue live. User image and company logo

**Comment by sanjayacloud** [comment]
I am having the same issue. Is his fixed?

**Comment by mohitpanjwani** [comment]
This issue has been fixed on the recent update. 

Please upgrade your crater version if you're on an older version.
