### ISSUE TITLE
Currency position

### ISSUE THREAD

**Issue by BIIINO** [bytefury/crater#414]
Hello,

i found closed feature request for euro € position. In Slovakia euro symbol have to be behind price so 100€, not €100. How can i change it on PDF please? 

Thank you

**Comment by BIIINO** [comment]
I think, issue is in this file:

/crater/database/seeders/CurrenciesTableSeeder.php

In currency euro section is missing line:

'swap_currency_symbol' => true

But when i add that line, nothing change, also i try add new test currency:

 [
                'name' => 'BINO EURO',
                'code' => 'BNE',
                'symbol' => 'BN',
                'precision' => '2',
                'thousand_separator' => ' ',
                'decimal_separator' => ',',
                'swap_currency_symbol' => true
 ],


but also this currency is not avalaible in app, same when i change for example symbol under Euro currency section from € to @, in application is still showing € .

Of course after each change what i have done, i run "yarn dev"

BUT when i create cutsom language and add it to:
/crater/resources/assets/js/plugins/i18n.js
and
/www/crater/config/crater.php

Everythink work like a charm, language working and and showing in webinterface

Using:

latest build and apache on centos 7


Please any hint.

Thank you

**Comment by mohitpanjwani** [comment]
The currencies are stored in the database, so in order to change something there, you need to update the specific currency in the currencies table. 

The file which you mentioned is a Seeder file, which is only used when you run the installation wizard for the first time in order to create these currencies in the database. 

I'll close this issue as the solution I mentioned should work perfectly but let me know if there's anything else.
