### ISSUE TITLE
SQL Error 

### ISSUE THREAD

**Issue by tobax99** [bytefury/crater#463]
Hi, 

can you help me with this error, how to fix it?
Crater Version 4.0.2

![image](https://user-images.githubusercontent.com/40302647/117612819-20342180-b166-11eb-9267-c63a7e69a05f.png)

**Comment by mwikala** [comment]
Hi @tobax99 what database driver are you using?

It looks like you might be trying to use Postgres? If so, I think you might have identified a bug here.

Postgres expects all boolean values to be type casted to true/false where as myself store's these values as 1/0. It's a simple fix, I'll update the issue with more once complete.

**Comment by tobax99** [comment]
Hi @mwikala, yes you're right - i am using postgres sql and it has worked until the last server restart. 
Thank you very much for your help. can you also tell me how i can fix this manually without an update? currently this bug does not allow crater to start...

**Comment by mwikala** [comment]
The quickest way to fix this, @tobax99,  is to edit `app\Models\FileDisk.php` to be like below:

```php
protected $guarded = [
    'id'
];

// Add the below line
protected $casts = ['set_as_default' => 'boolean'];
```

**Comment by tobax99** [comment]
@mwikala  - After Edit FileDisk.php the Error still occurs. Additional Info:

![image](https://user-images.githubusercontent.com/40302647/118414072-dfc32f00-b6a2-11eb-8b39-2cfba4f662f9.png)

Did I miss something? Crater Version 4.0.2

**Comment by mwikala** [comment]
Okay after doing some digging, this seems to just be an issue in PHP 8.0.5, best you can do to get it working is downgrade PHP 8.0.4 otherwise you'll have to make a lot of manual edits and I'm not sure where these all are.

See [this issue on the Laravel Framework](https://github.com/laravel/framework/issues/37215)

Another alternative, but like I mentioned you'd have to do this everywhere, is to change the `true` to be a string `'true'` since it won't try casting that when checking the database.

**Comment by tobax99** [comment]
@mwikala Thanks for finding out! 
I have currently installed 7.4.18, but will now try to update to 8.0.4.
It seems to be this PHP Bug, the change to `'true' `  at least leads to the login panel.
