### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Mak-3000** [bytefury/crater#51]
Hi all,
I've tried to install the app many times on many servers, but it always failed!
On a server using Mariadb, it gives an error due to JSON.
On server using Mysql 5.7 it gives error "wizard.errors.undefined" in database installation step!
I don't know where is the issue exactly, any body can help?

Thank you.

**Comment by lamtszhin0528** [comment]
I have same issue, I was using QNAP NAS for web server and Mariadb,
also it will be failure when I use GoDaddy hosting service.

**Comment by mohitpanjwani** [comment]
Hey, this issue should be fixed in the latest release. Even if it fails, it should provide proper error as to what's wrong with the server to make it easier for you to fix the issue.

Please re-download the latest version and check it out.

I'm closing this issue but you can re-open it if it still fails.
