### ISSUE TITLE
Customer e-mail address should not be unique

### ISSUE THREAD

**Issue by Pazekal90** [bytefury/crater#528]
Problem: As a Freelancer / small business i have clients that have multiple businesses and want separate invoices for their businesses. By adding those business as separate customers i ran into problems because the email address needs to be unique at the moment. 

I now have to add mail redirections to get around this problem. 

Solution: The e-mail address should not be unique for customers.

**Comment by mohitpanjwani** [comment]
In the next update we've planned a customer portal for customers and the login system works based on email + password so the email has to be unique otherwise its not possible to identify the customer. 

One way to fix this would be to add a different `notification_email` field which will be used to notify the customers but the account email has to be different.

**Comment by Pazekal90** [comment]
Ahh ok. 👍
