### ISSUE TITLE
Add payment to partial paid invoice

### ISSUE THREAD

**Issue by egrueda** [bytefury/crater#550]
When adding a partial payment for the first time to an invoice, clicking Payment > Add payment, I can select a client and then I can pick one client's invoice from the dopdown.

But when I get the next/missing payment for that invoice, I can't apply that payment to the partial paid invoice as it doesn't show up in the invoices dropdown.
Seems like only unpaid invoices are shown there, but all non fully paid invoices should be shown

Ajax request says:
/api/v1/invoices?customer_id=1234&status=UNPAID
But partially paid invoices should show up too

**Comment by mohitpanjwani** [comment]
Hey, this issue is already fixed here but we still haven't deployed an update so it might not be working for you, if you downloaded Crater manually. 

https://github.com/bytefury/crater/commit/8219d192227cd0c11f15c9402aad1c72ad3dbbe6#diff-1ce390f868e262a719bbc1c679147b717f691049165fa18fba9986848f71f437R542

If you need this fixed urgently, just replace the `public/assets` folder from here: https://github.com/bytefury/crater/tree/master/public/assets.

**Comment by egrueda** [comment]
Thanks! I have manually downloaded those files and problem is fixed.
Hope you can deploy an official update soon. Best regards.
