### ISSUE TITLE
wizard.errors.undefined

### ISSUE THREAD

**Issue by sykot** [bytefury/crater#57]
Hello,
When I tired to install, it shows "wizard.errors.undefined" on "Site URL & Database" step.
Can anyone please help?
Thanks

**Comment by Mak-3000** [comment]
The same issue here https://github.com/bytefury/crater/issues/51

**Comment by mohitpanjwani** [comment]
Hey, this issue should be fixed in the latest release.  Even if it fails, it should provide proper error as to what's wrong with the server to make it easier for you to fix the issue.

Please re-download the latest version and check it out. 

I'm closing this issue but you can re-open it if it still happens for you.
