### ISSUE TITLE
Not going forward on mail server on "ONBOARDING"

### ISSUE THREAD

**Issue by janakkapadia** [bytefury/crater#58]
Stuck on loading on OnBoarding step 4 which mail driver get.

**Comment by mohitpanjwani** [comment]
Please mention the below details or recreate the issue with the bug-report issue template.

**Describe the bug**
A clear and concise description of what the bug is.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Please complete the following information:**
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]

**Comment by ekaranja-lco** [comment]
Hi, I'm getting the same issue.
All steps are successful but step 4 won't pass. No errors.
After step 3 the **save** button displays a loading status without having submitted the form.

![Screenshot from 2019-12-27 13-35-33](https://user-images.githubusercontent.com/59202557/71514151-6d379080-28ae-11ea-9d6e-a8cf2d4e93ae.png)

Crater v2.1.0
Am using PHP 7.4
Database: mysql8.0

OS: Ubuntu19.10
Browser: Chrome

**Comment by peterarends** [comment]
I was having the same issue. For me, it turned out to be database credentials that were not correct. Check the error in the developer console.

**Comment by ekaranja-lco** [comment]
I guess my server setup was wrong somehow.
Also I had not granted the right folder permissions.
I installed [valet](https://cpriego.github.io/valet-linux/) and it worked like a charm.

**Comment by adeel94mirza** [comment]
Facing the same issue. I am getting the following error in console
![image](https://user-images.githubusercontent.com/54454328/87689719-f9a19600-c7a1-11ea-89d6-b1fd6daeef01.png)

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on V4. 

Please re-open it if you still encounter this.
