### ISSUE TITLE
Unable to connect to the DB with Provided Values

### ISSUE THREAD

**Issue by trapaholics** [bytefury/crater#91]
Hi, 

I'm facing this problem while configuring the app. The installer fails to migrate the tables. I created the database and made sure it's empty.

![Screenshot 2019-12-21 at 17 22 55](https://user-images.githubusercontent.com/59117657/71309354-f6b31280-2417-11ea-9e2b-f3e5cb5a423a.png)

I double-checked the DB credentials. When I enter wrong credentials, I get the below response:

![Screenshot 2019-12-21 at 17 23 18](https://user-images.githubusercontent.com/59117657/71309384-3974ea80-2418-11ea-8ff9-d7180dbdd5dd.png)

I'm running Ubuntu Server 18.04, MySQL v5.7.28, PHP 7.3.12

Thanks

**Comment by ShekhSaifuddin007** [comment]
same here, but I'm on xampp

**Comment by surajjdhv** [comment]
Same here! I'm running a AWS EC2 instance and certain that the mysql values are correct

**Comment by mohitpanjwani** [comment]
Hey guys! I will try to reproduce this issue at morning.

Btw just to confirm, did you guys clone the repository with git or downloaded the zip file from craterapp.com?

**Comment by surajjdhv** [comment]
Thanks for the response. I have cloned the repository and installed manually.

**Comment by ShekhSaifuddin007** [comment]
We clone it by git clone @mohitpanjwani

**Comment by trapaholics** [comment]
Thanks for the response @mohitpanjwani. I, too, cloned from the repository

**Comment by surajjdhv** [comment]
@mohitpanjwani I can confirm that downloading zip from the portal does not cause this issue.

**Comment by mohitpanjwani** [comment]
Hey guys! Thanks for reporting the issue. 

This is actually a file permission issue. It does not happen for me when I test it using Laravel Valet on my mac but I think on Windows and Linux, you will need to set proper file permissions on `.env` file so it allows the app to make changes for installation. 

Also, I've fixed the error message from "Unable to connect to DB with provided configuration" to "Cannot write configuration to .env file. Please check its file permissions" to make it easier for users to fix the issue. 

@surajjdhv Thanks for the confirmation, it works when downloading the zip directly because the zip file comes with a .env by default.

**Comment by trapaholics** [comment]
Surely it was a permission issue. Run a few permission commands and resolved the issue. @mohitpanjwani Thanks again for your quick response. I can close this now
